// scripts/audio.mjs - Run with `npm run audio` after adding or removing recordings.
// Rebuilds audio/manifest.json from the files in audio/ and rewrites audio/RECORDING-LIST.md,
// the checklist of every clip the app can play.
import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, extname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { neededClips } from '../logic.js';

const AUDIO_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'audio');
const FOLDERS = ['letters', 'words', 'pairs', 'sentences'];
const EXTENSIONS = ['.mp3', '.m4a', '.aac', '.ogg', '.wav', '.webm'];

// The sound each letter makes in this course, with a word from the lessons to anchor it
const LETTER_SOUNDS = {
  a: ['/æ/', 'at'], b: ['/b/', 'bat'], c: ['/k/', 'cat'], d: ['/d/', 'dot'], e: ['/e/', 'bed'],
  f: ['/f/', 'fan'], g: ['/g/', 'gut'], h: ['/h/', 'hot'], i: ['/ɪ/', 'pin'], j: ['/dʒ/', 'jam'],
  k: ['/k/', 'kid'], l: ['/l/', 'leg'], m: ['/m/', 'map'], n: ['/n/', 'nap'], o: ['/ɒ/', 'hot'],
  p: ['/p/', 'pin'], q: ['/kw/', 'quiz'], r: ['/r/', 'rod'], s: ['/s/', 'sun'], t: ['/t/', 'tip'],
  u: ['/ʌ/', 'sun'], v: ['/v/', 'van'], w: ['/w/', 'win'], x: ['/ks/', 'box'], y: ['/j/', 'yes'],
  z: ['/z/', 'zip']
};

function sayFor({ kind, text }) {
  if (kind === 'letter') {
    const [ipa, example] = LETTER_SOUNDS[text.toLowerCase()] || ['', ''];
    return `the sound ${ipa} as in "${example}", not the letter name`;
  }
  if (kind === 'pair') {
    const sounds = text.toLowerCase().split('').map(ch => (LETTER_SOUNDS[ch] || [ch])[0]).join(' + ');
    return `"${text}": blend ${sounds} into one syllable`;
  }
  if (text.toLowerCase() === 'a') return `the word "a" as in "a cat" (/ə/), not the letter sound`;
  return `"${text}"`;
}

// key (e.g. "letters/b") -> file path inside audio/ (e.g. "letters/b.mp3")
function findRecordings() {
  const files = {};
  FOLDERS.forEach(folder => {
    const dir = join(AUDIO_DIR, folder);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    readdirSync(dir).forEach(name => {
      const ext = extname(name).toLowerCase();
      if (!EXTENSIONS.includes(ext)) return;
      files[`${folder}/${name.slice(0, -ext.length)}`] = `${folder}/${name}`;
    });
  });
  return files;
}

const clips = neededClips();
const files = findRecordings();
const neededKeys = new Set(clips.map(c => c.key));
const manifestFiles = Object.fromEntries(
  Object.keys(files).filter(k => neededKeys.has(k)).sort().map(k => [k, files[k]])
);
const unused = Object.keys(files).filter(k => !neededKeys.has(k)).map(k => files[k]);

writeFileSync(join(AUDIO_DIR, 'manifest.json'), JSON.stringify({ files: manifestFiles }, null, 2) + '\n');

const recorded = Object.keys(manifestFiles).length;
const sections = [
  ['letter', 'Letter sounds', 'letters'],
  ['word', 'Words and sight words', 'words'],
  ['pair', 'Letter pairs', 'pairs'],
  ['sentence', 'Sentences', 'sentences']
];
const lines = [
  '# Recording list',
  '',
  `Generated by \`npm run audio\`. Don't edit by hand. **${recorded} of ${clips.length} clips recorded.**`,
  '',
  'Until a clip is recorded, the app uses the browser\'s speech synthesis, which reads single letters',
  'as their names ("bee" for b) and guesses at letter pairs. Recorded clips fix that.',
  '',
  '## How to record',
  '',
  '1. Use one clear, natural speaker for every clip, in a quiet room. A phone voice-memo app is fine.',
  '2. Letter sounds are the sound only, short and clean: /b/, not "buh" and not "bee".',
  '3. Trim the silence at both ends. Mono, about 64 kbps, as `.mp3` or `.m4a` (both play on iPhone and Android).',
  '4. Save each file under the exact name below (lowercase), e.g. `audio/words/bat.mp3`.',
  '5. Run `npm run audio` to update `audio/manifest.json` and this list, then commit both with the clips.',
  '6. When you replace an existing clip, also bump `CACHE_NAME` in `service-worker.js` so installed apps fetch it again.',
  ''
];
sections.forEach(([kind, title, folder]) => {
  const items = clips.filter(c => c.kind === kind);
  if (!items.length) return;
  lines.push(`## ${title} (\`audio/${folder}/\`)`, '', '| Done | File | Say |', '|---|---|---|');
  items.forEach(c => {
    const file = manifestFiles[c.key] || `${c.key}.mp3`;
    lines.push(`| ${manifestFiles[c.key] ? '✅' : '⬜'} | \`${file}\` | ${sayFor(c)} |`);
  });
  lines.push('');
});
if (unused.length) {
  lines.push('## Files not used by the app', '', 'Check these names for typos:', '', ...unused.map(f => `- \`${f}\``), '');
}
writeFileSync(join(AUDIO_DIR, 'RECORDING-LIST.md'), lines.join('\n'));

console.log(`${recorded} of ${clips.length} clips recorded.`);
if (unused.length) console.log(`Not used by the app (check the names): ${unused.join(', ')}`);
